sudo: required

services:
    - docker

before_install:
  - docker build -t usrnotfound/docker-react -f Dockerfile.dev .

script:
  - docker run usrnotfound/docker-react npm run

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  name: "docker-react"
  env: "DockerReact-env"
  bucket_name : "elasticbeanstalk-ap-southeast-2-474781482154"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"